# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('site_lat', models.DecimalField(decimal_places=9, default=48.0, max_digits=12)),
                ('site_lon', models.DecimalField(decimal_places=9, default=20.0, max_digits=12)),
                ('site_status', models.CharField(choices=[(b'Up', b'UP'), (b'Down', b'DOWN')], max_length=4)),
                ('cpe_cell', models.CharField(max_length=50)),
                ('cpe_imei', models.IntegerField()),
                ('cpe_imsi', models.IntegerField()),
                ('cpe_lat', models.DecimalField(decimal_places=9, default=48.0, max_digits=12)),
                ('cpe_lon', models.DecimalField(decimal_places=9, default=20.0, max_digits=12)),
                ('cpe_status', models.CharField(choices=[(b'Up', b'UP'), (b'Down', b'DOWN')], max_length=4)),
            ],
        ),
    ]
