# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(help_text=b'Starting point', max_length=50)),
                ('site_lat', models.FloatField(default=48.0, help_text=b'Starting point latitude')),
                ('site_lon', models.FloatField(default=20.0, help_text=b'Starting point longitude')),
                ('cpe_cell', models.CharField(max_length=50)),
                ('cpe_imei', models.IntegerField()),
                ('cpe_imsi', models.IntegerField()),
                ('cpe_name', models.CharField(help_text=b'Ending point name', max_length=50)),
                ('cpe_lat', models.FloatField(default=48.0, help_text=b'Ending point latitude')),
                ('cpe_lot', models.FloatField(default=20.0, help_text=b'Ending point longitude')),
            ],
        ),
    ]
