# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalcoverage',
            name='cpe_lot',
        ),
        migrations.AddField(
            model_name='signalcoverage',
            name='cpe_lon',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='signalcoverage',
            name='cpe_status',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signalcoverage',
            name='site_status',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signalcoverage',
            name='cpe_lat',
            field=models.FloatField(default=48.0),
        ),
        migrations.AlterField(
            model_name='signalcoverage',
            name='cpe_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signalcoverage',
            name='site_lat',
            field=models.FloatField(default=48.0),
        ),
        migrations.AlterField(
            model_name='signalcoverage',
            name='site_lon',
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name='signalcoverage',
            name='site_name',
            field=models.CharField(max_length=50),
        ),
    ]
