# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20161213_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalcoverage',
            name='cpe_name',
        ),
        migrations.AlterField(
            model_name='signalcoverage',
            name='cpe_lat',
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name='signalcoverage',
            name='cpe_lon',
            field=models.FloatField(default=48.0),
        ),
        migrations.AlterField(
            model_name='signalcoverage',
            name='site_lat',
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name='signalcoverage',
            name='site_lon',
            field=models.FloatField(default=48.0),
        ),
    ]
