# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20161213_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalcoverage',
            name='cpe_lat',
            field=models.DecimalField(decimal_places=9, default=48.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='signalcoverage',
            name='cpe_lon',
            field=models.DecimalField(decimal_places=9, default=20.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='signalcoverage',
            name='cpe_status',
            field=models.CharField(choices=[(b'up', b'UP'), (b'down', b'DOWN')], max_length=4),
        ),
        migrations.AlterField(
            model_name='signalcoverage',
            name='site_lat',
            field=models.DecimalField(decimal_places=9, default=48.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='signalcoverage',
            name='site_lon',
            field=models.DecimalField(decimal_places=9, default=20.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='signalcoverage',
            name='site_status',
            field=models.CharField(choices=[(b'up', b'UP'), (b'down', b'DOWN')], max_length=4),
        ),
    ]
